"""Zero-knowledge bootstrapper for installing, configuring, importing, and running the app."""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import socket
import subprocess
import sys
import time
import webbrowser
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
CONFIG_FILE = PROJECT_DIR / "config.toml"
MINIMUM_PYTHON = (3, 11)


def prompt(message: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    answer = input(f"{message}{suffix}: ").strip()
    return answer or (default or "")


def confirm(message: str, default: bool = True) -> bool:
    choice = "Y/n" if default else "y/N"
    answer = input(f"{message} [{choice}]: ").strip().casefold()
    if not answer:
        return default
    return answer in {"y", "yes"}


def uv_command() -> list[str]:
    executable = shutil.which("uv")
    if executable:
        return [executable]
    if importlib.util.find_spec("uv") is not None:
        return [sys.executable, "-m", "uv"]
    if not sys.stdin.isatty() or not confirm("uv is required. Install it with pip now?"):
        raise SystemExit("Install uv from https://docs.astral.sh/uv/ and run this command again.")
    subprocess.run([sys.executable, "-m", "pip", "install", "--user", "uv"], check=True)
    return [sys.executable, "-m", "uv"]


def private_defaults() -> tuple[Path, Path, Path]:
    root = Path(os.environ.get("PORTFOLIO_BOOTSTRAP_ROOT", Path.home() / "PortfolioDashboard")).expanduser()
    return root / "source-files", root / "private-data", root / "cache"


def write_default_config(source_dir: Path, data_dir: Path, cache_dir: Path) -> None:
    for directory in (source_dir, data_dir, cache_dir):
        directory.expanduser().mkdir(parents=True, exist_ok=True)
    content = f"""# Generated by run.py. This file is private and ignored by Git.
source_dir = {json.dumps(str(source_dir.expanduser().resolve()))}
data_dir = {json.dumps(str(data_dir.expanduser().resolve()))}
cache_dir = {json.dumps(str(cache_dir.expanduser().resolve()))}
movement_database_file = "movements.sqlite3"
scan_downloads = false

primary_portfolio_id = "primary"
primary_portfolio_name = "Primary Portfolio"
since_2024_portfolio_ids = []

trade_republic_pattern = "broker_exports/*/*trade_republic*.csv"
fineco_pattern = "broker_exports/*/*fineco*.xlsx"
interactive_brokers_pattern = "broker_exports/*/*interactive_brokers*.pdf"
etoro_pattern = "broker_exports/*/*etoro*.xlsx"
revolut_pattern = "cash_exports/*/*account-statement*.csv"
intesa_pattern = "cash_exports/*/*account_operations*.xlsx"
bbva_pattern = "cash_exports/*/*bbva*.xls"
"""
    CONFIG_FILE.write_text(content, encoding="utf-8")


def configure() -> bool:
    if CONFIG_FILE.exists():
        print(f"Configuration: {CONFIG_FILE}")
        return False
    source_default, data_default, cache_default = private_defaults()
    print("\nFirst-time setup")
    print("Financial files remain outside the application repository.")
    if sys.stdin.isatty():
        source = Path(prompt("Statement archive directory", str(source_default))).expanduser()
        data = Path(prompt("Private database/configuration directory", str(data_default))).expanduser()
        cache = Path(prompt("Disposable cache directory", str(cache_default))).expanduser()
    else:
        source, data, cache = source_default, data_default, cache_default
    write_default_config(source, data, cache)
    print(f"Created private configuration: {CONFIG_FILE}")
    print_file_layout(source)
    return True


def print_file_layout(source_dir: Path) -> None:
    print("\nSupported files can be imported in the browser or placed under:")
    print(f"  {source_dir / 'broker_exports' / 'trade_republic'}  (Trade Republic CSV)")
    print(f"  {source_dir / 'broker_exports' / 'fineco'}  (Fineco XLSX)")
    print(f"  {source_dir / 'broker_exports' / 'interactive_brokers'}  (Interactive Brokers PDF)")
    print(f"  {source_dir / 'broker_exports' / 'etoro'}  (eToro XLSX)")
    print(f"  {source_dir / 'broker_exports' / 'manual'}  (Personal trades CSV/XLSX)")
    print(f"  {source_dir / 'cash_exports' / 'revolut'}  (Revolut CSV)")
    print(f"  {source_dir / 'cash_exports' / 'intesa'}  (Intesa XLSX)")
    print(f"  {source_dir / 'cash_exports' / 'bbva'}  (BBVA XLS)")
    print("The importer creates these folders and filenames automatically.")


def sync_environment(uv: list[str]) -> None:
    print("\nInstalling/updating the local application environment…")
    subprocess.run([*uv, "sync", "--frozen"], cwd=PROJECT_DIR, check=True)


def import_files(uv: list[str], files: list[str], source: str = "auto") -> None:
    if not files:
        return
    command = [*uv, "run", "--frozen", "python", "scripts/import_statements.py", "--source", source, *files]
    subprocess.run(command, cwd=PROJECT_DIR, check=True)


def prompt_for_imports(uv: list[str]) -> None:
    if not sys.stdin.isatty() or not confirm("Import statement files now?", default=False):
        return
    print("Enter one CSV/XLS/XLSX/PDF path per line. Press Return on an empty line when finished.")
    files: list[str] = []
    while True:
        value = input("File: ").strip()
        if not value:
            break
        files.append(value)
    import_files(uv, files)


def wait_for_server(process: subprocess.Popen[bytes], port: int, timeout: float = 90.0) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise SystemExit(f"Dashboard exited with status {process.returncode}")
        with socket.socket() as connection:
            connection.settimeout(0.2)
            if connection.connect_ex(("127.0.0.1", port)) == 0:
                return
        time.sleep(0.15)
    process.terminate()
    raise SystemExit(f"Dashboard did not start on port {port} within {timeout:.0f} seconds")


def run_server(uv: list[str], port: int, open_browser: bool) -> int:
    command = [
        *uv,
        "run",
        "--frozen",
        "python",
        "-c",
        f"import app; app.app.run(host='127.0.0.1', port={port})",
    ]
    print("\nStarting the dashboard (the first launch may take up to a minute)…")
    process = subprocess.Popen(command, cwd=PROJECT_DIR)
    try:
        wait_for_server(process, port)
        url = f"http://127.0.0.1:{port}"
        print(f"\nPortfolio Dashboard is running at {url}")
        print("Press Ctrl+C to stop it.")
        if open_browser:
            webbrowser.open(url)
        return process.wait()
    except KeyboardInterrupt:
        print("\nStopping dashboard…")
        process.terminate()
        try:
            return process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            process.kill()
            return process.wait()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Install, configure, import data, and run Portfolio Dashboard")
    parser.add_argument("--setup", action="store_true", help="configure and install without starting the server")
    parser.add_argument("--import", dest="import_paths", nargs="+", metavar="FILE", help="import statements before starting")
    parser.add_argument("--source", default="auto", help="source id for --import (default: automatic detection)")
    parser.add_argument("--port", type=int, default=8050)
    parser.add_argument("--no-browser", action="store_true")
    return parser.parse_args()


def main() -> int:
    if sys.version_info < MINIMUM_PYTHON:
        raise SystemExit("Python 3.11 or newer is required")
    args = parse_args()
    first_setup = configure()
    uv = uv_command()
    sync_environment(uv)
    if args.import_paths:
        import_files(uv, args.import_paths, args.source)
    elif first_setup:
        prompt_for_imports(uv)
    if args.setup:
        print("\nSetup complete. Run `python run.py` to start the dashboard.")
        return 0
    return run_server(uv, args.port, not args.no_browser)


if __name__ == "__main__":
    raise SystemExit(main())
